### ISSUE TITLE
Hopper flag is not respected when Lithium is installed

### ISSUE THREAD

**Issue by MojiRS** [QuiltServerTools/HeyThatsMine#15]
Lithium optimizes hopper behavior, and whatever changes it makes causes hoppers to still be able to insert/remove items from containers flagged with '/htm flag HOPPERS false'.

The issue happens consistently for all containers with only Hey That's Mine and Lithium installed.

Let me know if I should open an issue with Lithium instead - I figured it would be easier to add compatibility from your side, but I could be completely wrong.

**Versions:**
Hey That's Mine 1.1.3
Lithium 0.7.3

**Comment by PotatoPresident** [comment]
Talked to Caffine, we're working on it

**Comment by Carlosjrlu** [comment]
May I ask, any progress with this issue?

**Comment by cpm9** [comment]
Yeah this is game breaking. Had some players come through and rob our entire server this way, was a nightmare to sort through the consolidated items afterwards...

**Comment by PotatoPresident** [comment]
Current workaround is to add `mixin.block.hopper=false` to `lithium.properties` config file. Will add this to mod description.

**Comment by youstube-1** [comment]
There's no config for mixin.block.hopper=false? or at least this didn't work for me.

**Comment by arnokeesman** [comment]
just add a line with `mixin.block.hopper=false` to `/config/lithium.properties`

**Comment by arnokeesman** [comment]
just add a line with `mixin.block.hopper=false` to `/config/lithium.properties`

**Comment by youstube-1** [comment]
Looking at the lithium config page (https://github.com/CaffeineMC/lithium-fabric/wiki/Configuration-File), I don't see a config for that. Is it just not in the for some reason?
