### ISSUE TITLE
Crash when Admin tries accessing nonadmin locked chest

### ISSUE THREAD

**Issue by TwixWolf** [QuiltServerTools/HeyThatsMine#18]
[crash-2021-08-12_02.53.34-server.txt](https://github.com/QuiltServerTools/HeyThatsMine/files/6972548/crash-2021-08-12_02.53.34-server.txt)

I was walking around and tested trying to enter a locked chest of a players.  I crashed when attempting.  I am op on the modded server.

**Comment by PotatoPresident** [comment]
Your using the 1.17.1 version
