### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Fossil-F** [QuiltServerTools/HeyThatsMine#19]
I would like two features added:
1: Admin Command - Forced Ownership Transfer.
This would be an extension to the /htm transfer command where it would only be available for admins and it would like:
/htm transfer (from) (to),
Instead of the normal one:
/htm transfer (to).

2: Addition of anvils and enchantment tables into the list of locked blocks.
Pretty straightforward, anvils are open to all as well as enchantment tables, would be nice to have the ability to make this stuff lockable.

**Comment by Neubulae** [comment]
Anvils and ench. tables are not lockable entities meaning locking them would require extra work

**Comment by PotatoPresident** [comment]
> 1: Admin Command - Forced Ownership Transfer.
Players with OP level 2 or the `htm.admin` permission should already be able to transfer container ownership to whoever they want, regardless of who actually owns it. Unless you mean transfer all containers owned by them, which isn't possible as its stored per container.
> 2: Addition of anvils and enchantment tables into the list of locked blocks.
Not possible as these don't implement the vanilla `LockableContainerBlockEntity` system which HTM uses.
