### ISSUE TITLE
Can't open own chests after dying, need to disconnect and rejoin for it to work again

### ISSUE THREAD

**Issue by cpm9** [QuiltServerTools/HeyThatsMine#21]
Players on my server have been reporting that sometimes after they die and respawn they are unable to access their own chests or their trusted chests until they disconnect and reconnect. I have seen some server console messages that I think are related at the same time and for the same player that reports the problem.

![image](https://user-images.githubusercontent.com/82549089/144539566-a111727e-3712-4654-bea4-f47852fc0d52.png)

Minecraft: 1.18
Server: fabric loader 0.12.8, fabric api 0.43.1, htm-1.1.4
Client: vanilla 1.18

**Comment by cpm9** [comment]
![image](https://user-images.githubusercontent.com/82549089/144541585-376fa03b-44cb-4f08-8099-0bd6d688c1ba.png)
Sometimes the message appears hundreds or thousands of times

**Comment by cpm9** [comment]
@PotatoPresident <3

**Comment by PotatoPresident** [comment]
I'll look into it

**Comment by cpm9** [comment]
This is no longer happening with fabric api 0.46.6 and fabric loader 0.13.3
