### ISSUE TITLE
[Feature Request] Add a few items

### ISSUE THREAD

**Issue by Felix5566** [QuiltServerTools/HeyThatsMine#23]
I am using Fabric 1.18.1 with Java 17

Is it possible to add the following items?
minecraft:oak_door
minecraft:iron_door
minecraft:oak_trapdoor
minecraft:composter
minecraft:chipped_anvil

**Comment by PotatoPresident** [comment]
Anvils maybe, but unfortunately the rest can't be done as they aren't block entities.
