### ISSUE TITLE
Cancel current action

### ISSUE THREAD

**Issue by CoreBytee** [QuiltServerTools/HeyThatsMine#8]
Hey there!

I have a small improvement for your mod:

Allow users to cancel the current lock action:

Right now:
when you use /htm set PRIVATE or any other action it says in chat: "select a block to lock"

What should it be:
When you use /htm set PRIVATE or any other action, the chat says: "select a block to lock or click **here** to cancel"

Thanks!

**Comment by yitzy299** [comment]
Will do this myself

**Comment by PotatoPresident** [comment]
It would semi difficult to add and your can really just cancel it by clicking any other block.
